-- Copyright (c) Steve Evans 2007 
-- steve@topaz.myzen.co.uk 
-- This code is licenced under the BSD licence. For details see $INSTANCE_ROOT/LICENCE 
--  

-- GENERATED BY TRAD4 
delete from outright_book_outright_trades;
insert into outright_book_outright_trades values ( 6, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0 );
