-- Copyright (c) Steve Evans 2007 
-- steve@topaz.myzen.co.uk 
-- This code is licenced under the BSD licence. For details see $INSTANCE_ROOT/LICENCE 
--  

-- GENERATED BY TRAD4 
delete from repo_book_repo_trades;
insert into repo_book_repo_trades values ( 8, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0 );
