
-- GENERATED BY TRAD4 
delete from trade_couponInterval;
insert into trade_couponInterval values ( 20, 1, 'A', 0 );
insert into trade_couponInterval values ( 30, 1, 'A', 0 );
insert into trade_couponInterval values ( 40, 1, 'A', 0 );
