
// GENERATED BY TRAD4 

// Please see the comment at the top of orrery/gen/objects/body_macros.h
//  to see what's in-scope.

#include <cmath>
#include <iostream>
#include <iomanip>

#include "body_wrapper.c"

using namespace std;

int calculate_body( obj_loc_t obj_loc, int id )
{
    double r(0.0);
    double a(0.0);
    double ax(0.0);
    double ay(0.0);

    if ( !object_init(id) )
    {
        body_counter = 0;

        body_position_x( body_counter ) = body_initial_position_x;
        body_position_y( body_counter ) = body_initial_position_y;

        body_velocity_x( body_counter ) = body_initial_velocity_x;
        body_velocity_y( body_counter ) = body_initial_velocity_y;
    }
    else
    {
        body_counter++;

        for ( int i=0 ; i < NUM_OTHER_BODIES ; i++ )
        {
            r = sqrt( pow(( body_position_x( body_counter-1 ) - other_bodies_position_x( i, body_counter-1 )), 2 ) + pow(( body_position_y( body_counter-1 ) - other_bodies_position_y( i, body_counter-1 )), 2 ));

            a = ( G * other_bodies_mass(i) ) / pow( r, 2 );

            ax = (( body_position_x( body_counter-1 )  - other_bodies_position_x( i, body_counter-1 ) ) / r ) * -a;
            ay = (( body_position_y( body_counter-1 )  - other_bodies_position_y( i, body_counter-1 ) ) / r ) * -a;

            body_velocity_x( body_counter ) = body_velocity_x( body_counter-1 ) + ( ax * DT );
            body_velocity_y( body_counter ) = body_velocity_y( body_counter-1 ) + ( ay * DT );

            body_position_x( body_counter ) = body_position_x( body_counter-1 ) + ( body_velocity_x( body_counter-1 ) * DT );
            body_position_y( body_counter ) = body_position_y( body_counter-1 ) + ( body_velocity_y( body_counter-1 ) * DT );

        }
    }

    cout << setprecision(20) 
        << object_name(id) << "|"
        << body_counter << "|"
        << body_position_x( body_counter ) << "|"
        << body_position_y( body_counter ) << "|"
        << body_velocity_x( body_counter ) << "|"
        << body_velocity_y( body_counter ) << "|"
        << r << "|"
        << a << "|"
        << ax << "|"
        << ay << endl;

    return 1;
}

