-- Copyright (c) Steve Evans 2009 
-- steve@topaz.myzen.co.uk 
-- This code is released under the BSD licence. For details see $APP_ROOT/LICENCE 

-- GENERATED BY TRAD4 
delete from addition;
insert into object values ( 5, 3, 2, "x", 2, 1 );
insert into addition values ( 5, 1, 2 );
