-- Copyright (c) Steve Evans 2009 
-- steve@topaz.myzen.co.uk 
-- This code is released under the BSD licence. For details see $APP_ROOT/LICENCE 

-- GENERATED BY TRAD4 
delete from feed;
insert into object values ( 1, 2, 1, "a", 2, 1 );
insert into feed values ( 1, 7 );
insert into object values ( 2, 2, 1, "b", 2, 1 );
insert into feed values ( 2, 14 );
insert into object values ( 3, 2, 1, "c", 2, 1 );
insert into feed values ( 3, 27 );
insert into object values ( 4, 2, 1, "c", 2, 1 );
insert into feed values ( 4, 11 );
