
// GENERATED BY TRAD4 

// Please see the comment at the top of fourier_transform/gen/objects/correlator_macros.h
//  to see what's in-scope.

#include <iostream>

#include "correlator_wrapper.c"

using namespace std;

int calculate_correlator( obj_loc_t obj_loc, int id )
{
    if ( ! object_init(id ) )
    {
        double frequency = BASE_FREQUENCY * id;

        for ( int i = 1 ; i <= SAMPLE_COUNT ; i++ )
        {
            correlator_harmonic[i] = sin ( ( frequency * 2 * i * id * PI ) / (double)SAMPLE_COUNT ) ;
        }

    }

    correlator_amplitude = 0.0;

    for ( int i = 1 ; i <= SAMPLE_COUNT ; i++ )
    {
        correlator_amplitude += source_wave[i] * correlator_harmonic[i];
    }

    return 1;
}

