
// GENERATED BY TRAD4 

// Please see the comment at the top of fourier_transform/gen/objects/correlator_macros.h
//  to see what's in-scope.

#include <iostream>

#include "correlator_wrapper.c"

using namespace std;

int calculate_correlator( obj_loc_t obj_loc, int id )
{
    if ( ! object_init(id ) )
    {
        for ( int i = 1 ; i <= SAMPLE_COUNT ; i++ )
        {
            correlator_harmonic[i] = sin ( ( 2 * i * id * PI ) / (double)SAMPLE_COUNT ) ;
        }

    }

    double accumulator(0.0);

    for ( int i = 1 ; i <= SAMPLE_COUNT ; i++ )
    {
        accumulator += source_wave[i] * correlator_harmonic[i];
    }

cout << "accumulator: " << accumulator << endl;

    return 1;
}

