
// GENERATED BY TRAD4 

// Please see the comment at the top of hello_world/gen/objects/world_macros.h
//  to see what's in-scope.

#include <iostream>

#include "world_wrapper.c"

using namespace std;

int calculate_world( obj_loc_t obj_loc, int id )
{
    // Does nothing.

    return 1;
}

