
-- GENERATED BY TRAD4 
delete from agg_many1_many1_array;
insert into agg_many1_many1_array values ( 9, 0, 80 );
insert into agg_many1_many1_array values ( 9, 1, 81 );
insert into agg_many1_many1_array values ( 9, 2, 82 );
insert into agg_many1_many1_array values ( 9, 3, 83 );
insert into agg_many1_many1_array values ( 9, 4, 84 );
insert into agg_many1_many1_array values ( 9, 5, 85 );
insert into agg_many1_many1_array values ( 9, 6, 86 );
insert into agg_many1_many1_array values ( 9, 7, 87 );
insert into agg_many1_many1_array values ( 9, 8, 88 );
insert into agg_many1_many1_array values ( 9, 9, 89 );
