
-- GENERATED BY TRAD4 
delete from many1_my_struct1;
insert into many1_my_struct1 values ( 80, 80, 80.0, 35 );
insert into many1_my_struct1 values ( 81, 81, 81.0, 35 );
insert into many1_my_struct1 values ( 82, 82, 82.0, 35 );
insert into many1_my_struct1 values ( 83, 83, 83.0, 35 );
insert into many1_my_struct1 values ( 84, 84, 84.0, 35 );
insert into many1_my_struct1 values ( 85, 85, 85.0, 35 );
insert into many1_my_struct1 values ( 86, 86, 86.0, 35 );
insert into many1_my_struct1 values ( 87, 87, 87.0, 35 );
insert into many1_my_struct1 values ( 88, 88, 88.0, 35 );
insert into many1_my_struct1 values ( 89, 89, 89.0, 35 );
