
-- GENERATED BY TRAD4 
delete from multi_struct_my_outers_my_inner_ms_ha;
insert into multi_struct_my_outers_my_inner_ms_ha values ( 5, 0, 0, 0, 0.0 );
insert into multi_struct_my_outers_my_inner_ms_ha values ( 5, 0, 0, 1, 0.1 );
insert into multi_struct_my_outers_my_inner_ms_ha values ( 5, 0, 0, 2, 0.2 );
insert into multi_struct_my_outers_my_inner_ms_ha values ( 5, 0, 0, 3, 0.3 );
insert into multi_struct_my_outers_my_inner_ms_ha values ( 5, 0, 0, 4, 0.4 );
insert into multi_struct_my_outers_my_inner_ms_ha values ( 5, 0, 0, 5, 0.5 );
insert into multi_struct_my_outers_my_inner_ms_ha values ( 5, 0, 0, 6, 0.6 );
insert into multi_struct_my_outers_my_inner_ms_ha values ( 5, 0, 0, 7, 0.7 );

insert into multi_struct_my_outers_my_inner_ms_ha values ( 5, 3, 2, 0, 32.0 );
insert into multi_struct_my_outers_my_inner_ms_ha values ( 5, 3, 2, 1, 32.1 );
insert into multi_struct_my_outers_my_inner_ms_ha values ( 5, 3, 2, 2, 32.2 );
insert into multi_struct_my_outers_my_inner_ms_ha values ( 5, 3, 2, 3, 32.3 );
insert into multi_struct_my_outers_my_inner_ms_ha values ( 5, 3, 2, 4, 32.4 );
insert into multi_struct_my_outers_my_inner_ms_ha values ( 5, 3, 2, 5, 32.5 );
insert into multi_struct_my_outers_my_inner_ms_ha values ( 5, 3, 2, 6, 32.6 );
insert into multi_struct_my_outers_my_inner_ms_ha values ( 5, 3, 2, 7, 32.7 );
