
-- GENERATED BY TRAD4 
delete from multi_struct_my_outers;
insert into multi_struct_my_outers values ( 5, 0, 99, 9.9 );
insert into multi_struct_my_outers values ( 5, 1, 199, 19.9 );
insert into multi_struct_my_outers values ( 5, 2, 299, 29.9 );
insert into multi_struct_my_outers values ( 5, 3, 399, 39.9 );
