
-- GENERATED BY TRAD4 
delete from tier1_struct_scalar_rates;
insert into tier1_struct_scalar_rates values ( 1, 0, 0, 4.0 );
insert into tier1_struct_scalar_rates values ( 1, 0, 1, 4.1 );
insert into tier1_struct_scalar_rates values ( 1, 0, 2, 4.2 );
