
-- GENERATED BY TRAD4 
delete from tier1_double_array;
insert into tier1_double_array values ( 1, 1.14 );
insert into tier1_double_array values ( 1, 2.14 );
insert into tier1_double_array values ( 1, 3.14 );
insert into tier1_double_array values ( 1, 4.14 );
insert into tier1_double_array values ( 1, 5.14 );
