
// GENERATED BY TRAD4 

// Please see the comment at the top of fourier_transform/gen/objects/source_macros.h
//  to see what's in-scope.

#include <iostream>

#include "source_wrapper.c"

using namespace std;

int calculate_source( obj_loc_t obj_loc, int id )
{
    if ( ! object_init(id ) )
    {
        for ( int i = 0 ; i <= SAMPLE_COUNT ; i++ )
        {
            source_wave[i] = sin ( ( 2 * i * PI ) / (double)SAMPLE_COUNT ) ;
        }
    }

    return 1;
}

