
// GENERATED BY TRAD4 

// Please see the comment at the top of simple_maths/gen/objects/b_macros.h
//  to see what's in-scope.

#include <iostream>

#include "b_wrapper.c"

using namespace std;

int calculate_b( obj_loc_t obj_loc, int id )
{
    // Does nothing.

    return 1;
}

