
// GENERATED BY TRAD4 

// Please see the comment at the top of simple_maths/gen/objects/x_macros.h
//  to see what's in-scope.

#include <iostream>

#include "x_wrapper.c"

using namespace std;

int calculate_x( obj_loc_t obj_loc, int id )
{
    x_out = a_out + b_out;

    return 1;
}

