
// GENERATED BY TRAD4 

// Please see the comment at the top of simple_maths/gen/objects/y_macros.h
//  to see what's in-scope.

#include <iostream>

#include "y_wrapper.c"

using namespace std;

int calculate_y( obj_loc_t obj_loc, int id )
{
    y_out = c_out - d_out;

    return 1;
}

