
-- GENERATED BY TRAD4 
delete from body;
insert into object values ( 1, 1, 1, "sun", 0, 1 );
insert into body values ( 1, 1.9891e+30, 9999 );

insert into object values ( 4, 1, 1, "earth", 0, 1 );
insert into body values ( 4, 5.9736e+24, 9999 );


