
// GENERATED BY TRAD4 

// Please see the comment at the top of gunfighter/gen/objects/monitor_macros.h
//  to see what's in-scope.

#include <iostream>

#include "monitor_wrapper.c"

using namespace std;

int calculate_monitor( obj_loc_t obj_loc, int id )
{
    if ( monitor_reset )
    {
        monitor_reset = 0;
        monitor_num_cycles = 0;
    }

    int local_num_alive(0);

    int local_survivor(0);

    for ( int i = 0 ; i < NUM_GUNFIGHTERS ; i++ )
    {
        local_num_alive = local_num_alive + gunfighters_alive(i);

        if ( gunfighters_alive(i) )
            local_survivor = monitor_gunfighters[i];
    } 


    if ( monitor_num_cycles == 1 )
    {
cout << "MNC: " << monitor_num_cycles << ", k: " << gunfighters_killed_whom(0) << endl;
        monitor_mr_black_first_shot = gunfighters_killed_whom(0);
    }

    if ( local_num_alive == 1 )
    {
        cout << "Done, " << local_survivor << " survived. MrBlack first shot at " << monitor_mr_black_first_shot  << endl;

        cout << endl;
        
        monitor_reset = 1;
    }

    monitor_num_cycles++;
    
    return 1;
}

