-- GENERATED BY TRAD4
delete from ir_curve_st_observables_dates;
insert into ir_curve_st_observables_dates values ( 1, 0, 148686 );
insert into ir_curve_st_observables_dates values ( 1, 1, 148715 );
insert into ir_curve_st_observables_dates values ( 1, 2, 148746 );
insert into ir_curve_st_observables_dates values ( 1, 3, 148837 );
insert into ir_curve_st_observables_dates values ( 1, 4, 148929 );
insert into ir_curve_st_observables_dates values ( 1, 5, 149021 );
insert into ir_curve_st_observables_dates values ( 1, 6, 149386 );
insert into ir_curve_st_observables_dates values ( 1, 7, 149751 );
insert into ir_curve_st_observables_dates values ( 1, 8, 150116 );
insert into ir_curve_st_observables_dates values ( 1, 9, 150482 );
insert into ir_curve_st_observables_dates values ( 1, 10, 150847 );
insert into ir_curve_st_observables_dates values ( 1, 11, 151212 );
insert into ir_curve_st_observables_dates values ( 1, 12, 151577 );
insert into ir_curve_st_observables_dates values ( 1, 13, 151943 );

