
// GENERATED BY TRAD4 

// Please see the comment at the top of vision_thing/gen/objects/input_macros.h
//  to see what's in-scope.

#include <iostream>

#include "input_wrapper.c"

using namespace std;

int calculate_input( obj_loc_t obj_loc, int id )
{
    if ( ! object_init( id ) )
    {
        input_image_number = 0;
    }
    else
    {
        if ( input_image_number < NUM_IMAGES-2 )
        {
            input_image_number = input_image_number + 1;
        }
        else
        {
            input_image_number = 0;
        }
    }

    cout << "input displaying " << input_image_number << endl;

/*
    for ( int row = 0 ; row < NUM_ROWS ; row++ )
    {
        for ( int col = 0 ; col < NUM_ROWS ; col++ )
        {
            cout << input_images_row_col( input_image_number, row, col );
        }

        cout << endl;
    }
*/

    return 1;
}

