-- Copyright (c) Steve Evans 2009 
-- steve@topaz.myzen.co.uk 
-- This code is released under the BSD licence. For details see $APP_ROOT/LICENCE 

-- GENERATED BY TRAD4 
delete from multiplication;
insert into object values ( 7, 5, 3, "z", 2, 1 );
insert into multiplication values ( 7, 5, 6 );
