-- Copyright (c) Steve Evans 2009 
-- steve@topaz.myzen.co.uk 
-- This code is released under the BSD licence. For details see $APP_ROOT/LICENCE 

-- GENERATED BY TRAD4 
delete from subtraction;
insert into object values ( 6, 4, 2, "y", 2, 1 );
insert into subtraction values ( 6, 3, 4 );
