-- GENERATED BY TRAD4
delete from ir_curve_st_observables_dates;
insert into ir_curve_st_observables_dates values ( 1, 148686, 148715, 148746, 148837, 148929, 149021, 149386, 149751, 150116, 150482, 150847, 151212, 151577, 151943 );

