
-- GENERATED BY TRAD4
delete from ir_curve_dates;
insert into ir_curve_dates values ( 1, 148686 );
insert into ir_curve_dates values ( 1, 148715 );
insert into ir_curve_dates values ( 1, 148746 );
insert into ir_curve_dates values ( 1, 148837 );
insert into ir_curve_dates values ( 1, 148929 );
insert into ir_curve_dates values ( 1, 149021 );
insert into ir_curve_dates values ( 1, 149386 );
insert into ir_curve_dates values ( 1, 149751 );
insert into ir_curve_dates values ( 1, 150116 );
insert into ir_curve_dates values ( 1, 150482 );
insert into ir_curve_dates values ( 1, 150847 );
insert into ir_curve_dates values ( 1, 151212 );
insert into ir_curve_dates values ( 1, 151577 );
insert into ir_curve_dates values ( 1, 151943 );

