// Copyright (c) Steve Evans 2008
// steve@topaz.myzen.co.uk
//

#include <iostream>
#include <sstream>
#include <vector>

#include "trad4.h"
#include "common.h"
#include "bond.h"
#include "discount_rate.h"
#include "interest_rate_feed.h"

#include "mysql/mysql.h"

MYSQL mysql;
MYSQL_RES *result;
MYSQL_ROW row;


extern void* obj_loc[NUM_OBJECTS+1];

// This is only called by the master thread, but it's a reader, so that's ok.
// These will be generated by trad4.
extern bool bond_need_refresh( int );
extern bool discount_rate_need_refresh( int id );

// Provided by the user.
extern void* calculate_bond( void* id );
extern void* calculate_discount_rate( void* id );
extern void* calculate_interest_rate_feed( void* id );


using namespace std;

void load_bond( int id );
void load_interest_rate_feeds();
void load_discount_rate( int id );

void load_interest_rate_feeds()
{
    ostringstream dbstream;
    dbstream << "select id, type, name from object where type=1";

    if(mysql_query(&mysql, dbstream.str().c_str()) != 0) {
        cout << __LINE__ << ": " << mysql_error(&mysql) << endl;
    }

    result = mysql_use_result(&mysql);

    int id;
    int type;
    std::string name;
    std::vector<int> interest_rates;

    while (( row = mysql_fetch_row(result) )) {

       id = atoi(row[0]);
       type = atoi(row[1]);
       name = row[2];

        obj_loc[id] = new interest_rate_feed;
        ((interest_rate_feed*)obj_loc[id])->last_published = 0;
        ((interest_rate_feed*)obj_loc[id])->status = STOPPED;
        ((interest_rate_feed*)obj_loc[id])->calculator_fpointer = &calculate_interest_rate_feed;
        ((interest_rate_feed*)obj_loc[id])->need_refresh_fpointer = 0; // It's a feed.
        ((interest_rate_feed*)obj_loc[id])->type = type;
    //    ((interest_rate_feed*)obj_loc[id])->name = 0;

        interest_rates.push_back( id );
    }

    mysql_free_result(result);

    vector<int>::iterator iter;

    for( iter = interest_rates.begin() ; iter < interest_rates.end() ; iter++ )
    {

        ostringstream dbstream;

        dbstream << "select asof, rate from interest_rate_vec where id = " << *iter;

        if(mysql_query(&mysql, dbstream.str().c_str()) != 0) {
            cout << __LINE__ << ": " << mysql_error(&mysql) << endl;
        }

        result = mysql_use_result(&mysql);

        int counter(0);

        while (( row = mysql_fetch_row(result) )) {
            ((interest_rate_feed*)obj_loc[*iter])->asof[counter] = atoi(row[0]);
            ((interest_rate_feed*)obj_loc[*iter])->rate[counter] = atof(row[1]);

            counter++;
        }
    }

    mysql_free_result(result);
}

void load_bonds()
{
    ostringstream dbstream;
    dbstream << "select o.id, type, name, b.coupon, b.start_date, b.maturity_date, b.coupons_per_year from object o, bond b where b.id = o.id and type=3";

    if(mysql_query(&mysql, dbstream.str().c_str()) != 0) {
        cout << __LINE__ << ": " << mysql_error(&mysql) << endl;
    }

    result = mysql_use_result(&mysql);

    while (( row = mysql_fetch_row(result) )) {

        int id = atoi(row[0]);

        obj_loc[id] = new bond;

        ((bond*)obj_loc[id])->last_published = 0;
        ((bond*)obj_loc[id])->status = STOPPED;
        ((bond*)obj_loc[id])->calculator_fpointer = &calculate_bond;
        ((bond*)obj_loc[id])->need_refresh_fpointer = &bond_need_refresh;
        ((bond*)obj_loc[id])->type = 0;
    //    ((bond*)obj_loc[id])->name = 0;

        ((bond*)obj_loc[id])->discount_rate = 2;
        ((bond*)obj_loc[id])->coupon = atof(row[3]);
        ((bond*)obj_loc[id])->start_date = atoi(row[4]);
        ((bond*)obj_loc[id])->maturity_date = atoi(row[5]);
        ((bond*)obj_loc[id])->coupons_per_year = atoi(row[6]);
        ((bond*)obj_loc[id])->ccy = 0;
        ((bond*)obj_loc[id])->price = 0.0;
        ((bond*)obj_loc[id])->dv01 = 0.0;

        cout << "New bond created" << endl;
    }

    mysql_free_result(result);
}

void load_discount_rate()
{
    ostringstream dbstream;
    dbstream << "select id from object where type=2";

    if(mysql_query(&mysql, dbstream.str().c_str()) != 0) {
        cout << __LINE__ << ": " << mysql_error(&mysql) << endl;
    }

    result = mysql_use_result(&mysql);

    while (( row = mysql_fetch_row(result) )) {

        int id = atoi(row[0]);

        obj_loc[id] = new discount_rate;

        ((discount_rate*)obj_loc[id])->last_published = 0;
        ((discount_rate*)obj_loc[id])->status = STOPPED;
        ((discount_rate*)obj_loc[id])->calculator_fpointer = &calculate_discount_rate;
        ((discount_rate*)obj_loc[id])->need_refresh_fpointer = &discount_rate_need_refresh;
        ((discount_rate*)obj_loc[id])->type = 0;
    //    ((discount_rate*)obj_loc[id])->name = 0;

        ((discount_rate*)obj_loc[id])->interest_rate_feed = 1;
        ((discount_rate*)obj_loc[id])->ccy = 0;

        cout << "New discount_rate created" << endl;

    }

    mysql_free_result(result);
}

void load_all()
{
    mysql_init(&mysql);

    if (!mysql_real_connect(&mysql,"localhost", "root", NULL,"trad4",0,NULL,0)) {
        cout << __LINE__ << " "  << mysql_error(&mysql) << endl;
    }

    load_interest_rate_feeds();
    load_bonds();
    load_discount_rate();
    
}





