// Copyright (c) Steve Evans 2007 
// steve@topaz.myzen.co.uk 
// This code is licenced under the BSD licence. For details see $INSTANCE_ROOT/LICENCE 
//  

// GENERATED BY TRAD4 

// Please see the comment at the top of bond_risk/gen/objects/outright_book_macros.h
//  to see what's in-scope.

#include <iostream>

#include "outright_book_wrapper.c"

using namespace std;

int calculate_outright_book( obj_loc_t obj_loc, int id )
{
    outright_book_pv=0;
    outright_book_pv_01=0;
    outright_book_pnl=0;    

    for ( int i=0 ; i < MAX_TRADES_PER_BOOK ; i++ )
    {
        if ( outright_book_outright_trades[i] )
        {
            outright_book_pv += outright_trades_pv(i);
            outright_book_pv_01 += outright_trades_pv_01(i);
            outright_book_pnl += outright_trades_pnl(i);
        }
    }

cout << "outright_book_pv: " << outright_book_pv << endl;

    return 1;
}

