
// GENERATED BY TRAD4 

// Please see the comment at the top of orrery/gen/objects/body_macros.h
//  to see what's in-scope.

#include <cmath>
#include <iostream>
#include <iomanip>

#include "body_wrapper.c"

using namespace std;

int calculate_body( obj_loc_t obj_loc, int id )
{
    if ( !object_init(id) )
    {
        body_position_x = body_initial_position_x;
        body_position_y = body_initial_position_y;

        body_velocity_x = body_initial_velocity_x;
        body_velocity_y = body_initial_velocity_y;
    }
    else
    {
        for ( int i=0 ; i < NUM_OTHER_BODIES ; i++ )
        {
            double r = sqrt( pow( body_position_x, 2 ) + pow( other_bodies_position_x(i), 2 ));

            double a = ( G * other_bodies_mass(i) ) / pow( r, 2 );

            double ax = (( body_position_x - other_bodies_position_x(i) ) / r ) * -a;
            double ay = (( body_position_y - other_bodies_position_y(i) ) / r ) * -a;

            body_velocity_x = body_velocity_x + ( ax * DT );
            body_velocity_y = body_velocity_y + ( ay * DT );

            body_position_x = body_position_x + ( body_velocity_x * DT );
            body_position_y = body_position_y + ( body_velocity_y * DT );

            cout << setprecision(20) 
                << object_name(id) << "|"
                << body_position_x << "|"
                << body_position_y << "|"
                << body_velocity_x << "|"
                << body_velocity_y << "|"
                << r << "|"
                << a << "|"
                << ax << "|"
                << ay << endl;
        }
    }

    return 1;
}

