
// GENERATED BY TRAD4 

// Please see the comment at the top of additive_synth/gen/objects/mixer_macros.h
//  to see what's in-scope.

#include <iostream>

#include "mixer_wrapper.c"

#include "write_wav_file.c"

using namespace std;

int calculate_mixer( obj_loc_t obj_loc, int id )
{
    for ( int i = 0 ; i < SAMPLE_COUNT ; i++ )
    {
        for ( int j = 0 ; j < NUM_HARMONICS_PER_MIXER ; j++ )
        {
            mixer_wave[i] += samples_wave( j, i ) / NUM_HARMONICS_PER_MIXER;
        }
    }

    if ( object_log_level(id) > NONE )
    {
        write_wav_file( mixer_wave, object_name(id) );
    }

    return 1;
}

