// Copyright (c) Steve Evans 2010 
// steve@topaz.myzen.co.uk 
// This code is licenced under the BSD licence. For details see $APP_ROOT/LICENCE 
//  

// GENERATED BY TRAD4 

// Please see the comment at the top of additive_synth/gen/objects/waveform_macros.h
//  to see what's in-scope.

#include <iostream>

#include "waveform_wrapper.c"

using namespace std;

int calculate_waveform( obj_loc_t obj_loc, int id )
{
    // Write me.

    return 1;
}

