
// GENERATED BY TRAD4 

// Please see the comment at the top of test_app/gen/objects/sample_macros.h
//  to see what's in-scope.

#include <iostream>

#include "sample_wrapper.c"

using namespace std;

int calculate_sample( obj_loc_t obj_loc, int id )
{
    // Does nothing.

    return 1;
}

