
// GENERATED BY TRAD4 

// Please see the comment at the top of test_suite/gen/objects/simple1_macros.h
//  to see what's in-scope.

#include <iostream>

#include "simple1_wrapper.c"

using namespace std;

#define simple2_s2_int ((simple2*)obj_loc[id])->s2_int

void calculate_simple1( obj_loc_t obj_loc, int id )
{
    // pub:
    simple1_s1_float = 3.45;

    T4_TEST( simple1_ix, 2 );
    T4_TEST( simple1_my_struct1( 0 ).x, 4 );
    T4_TEST( simple1_my_struct1_y(0), 5 );

/*
    cout << "TT2: " << simple1_my_struct1( 0 ).x << endl;
    cout << "TT2: " << simple1_my_struct1_y(0) << endl;
    // static:
    simple1_my_struct1_x(0) = 4;
    simple1_my_struct1_y(0) = 3.76;

    cout << "simple1_ix: " << simple1_ix << endl;
    cout << "TT: " << simple1_my_struct1( 0 ).y << endl;

*/

}

