// Copyright (c) Steve Evans 2007 
// steve@topaz.myzen.co.uk 
// This code is licenced under the BSD licence. For details see $INSTANCE_ROOT/LICENCE 
//  

// GENERATED BY TRAD4 

// Please see the comment at the top of bond_risk/gen/objects/calendar_macros.h
//  to see what's in-scope.

#include <iostream>

#include "calendar_wrapper.c"

using namespace std;

int calculate_calendar( obj_loc_t obj_loc, int id )
{
    // Does nothing.

    return 1;
}

