
-- GENERATED BY TRAD4 
delete from gunfighter;
insert into object values ( 1, 1, 1, "MrBlack", 0, 1 );
insert into gunfighter values ( 1, 0.3333, 2, 3, 999 );

insert into object values ( 2, 1, 2, "MrGrey", 0, 1 );
insert into gunfighter values ( 2, 0.6666, 1, 3, 999 );

insert into object values ( 3, 1, 3, "MrWhite", 0, 1 );
insert into gunfighter values ( 3, 1.0, 1, 2, 999 );


