-- Copyright (c) Steve Evans 2007 
-- steve@topaz.myzen.co.uk 
-- This code is licenced under the BSD licence. For details see $INSTANCE_ROOT/LICENCE 
--  

-- GENERATED BY TRAD4 
delete from calendar;
insert into object values ( 1, 1, 1, "calendar", 1, 1 );
insert into calendar values ( 1, 40403 );
