-- Copyright (c) Steve Evans 2007 
-- steve@topaz.myzen.co.uk 
-- This code is licenced under the BSD licence. For details see $INSTANCE_ROOT/LICENCE 
--  

-- GENERATED BY TRAD4 
delete from outright_book;
insert into object values ( 7, 7, 4, "outright_book", 1, 1 );
insert into outright_book values ( 7 );
