-- Copyright (c) Steve Evans 2007 
-- steve@topaz.myzen.co.uk 
-- This code is licenced under the BSD licence. For details see $INSTANCE_ROOT/LICENCE 
--  

-- GENERATED BY TRAD4 
delete from repo_book;
insert into object values ( 7, 7, 4, "REPO_GBP", 1, 1 );
insert into repo_book values ( 7 );

