
-- GENERATED BY TRAD4 
delete from many1;
insert into object values ( 80, 8, 1, "many1_80", 1, 1 );
insert into object values ( 81, 8, 1, "many1_81", 1, 1 );
insert into object values ( 82, 8, 1, "many1_82", 1, 1 );
insert into object values ( 83, 8, 1, "many1_83", 1, 1 );
insert into object values ( 84, 8, 1, "many1_84", 1, 1 );
insert into object values ( 85, 8, 1, "many1_85", 1, 1 );
insert into object values ( 86, 8, 1, "many1_86", 1, 1 );
insert into object values ( 87, 8, 1, "many1_87", 1, 1 );
insert into object values ( 88, 8, 1, "many1_88", 1, 1 );
insert into object values ( 89, 8, 1, "many1_89", 1, 1 );
insert into many1 values ( 80, 9.0, 9 );
insert into many1 values ( 81, 9.0, 9 );
insert into many1 values ( 82, 9.0, 9 );
insert into many1 values ( 83, 9.0, 9 );
insert into many1 values ( 84, 9.0, 9 );
insert into many1 values ( 85, 9.0, 9 );
insert into many1 values ( 86, 9.0, 9 );
insert into many1 values ( 87, 9.0, 9 );
insert into many1 values ( 88, 9.0, 9 );
insert into many1 values ( 89, 9.0, 9 );
