
-- GENERATED BY TRAD4 
delete from multi_struct_my_outers_my_inner_ms;
insert into multi_struct_my_outers_my_inner_ms values ( 5, 0, 0, 00 );
insert into multi_struct_my_outers_my_inner_ms values ( 5, 0, 1, 01 );
insert into multi_struct_my_outers_my_inner_ms values ( 5, 0, 2, 02 );
insert into multi_struct_my_outers_my_inner_ms values ( 5, 1, 0, 10 );
insert into multi_struct_my_outers_my_inner_ms values ( 5, 1, 1, 11 );
insert into multi_struct_my_outers_my_inner_ms values ( 5, 1, 2, 12 );
insert into multi_struct_my_outers_my_inner_ms values ( 5, 2, 0, 20 );
insert into multi_struct_my_outers_my_inner_ms values ( 5, 2, 1, 21 );
insert into multi_struct_my_outers_my_inner_ms values ( 5, 2, 2, 22 );
insert into multi_struct_my_outers_my_inner_ms values ( 5, 3, 0, 30 );
insert into multi_struct_my_outers_my_inner_ms values ( 5, 3, 1, 31 );
insert into multi_struct_my_outers_my_inner_ms values ( 5, 3, 2, 32 );
