
-- GENERATED BY TRAD4 
delete from multi_struct_my_outers_my_inner_ms_ha;
insert into multi_struct_my_outers_my_inner_ms_ha values ( 5, 0, 0, 0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.0, 0.0, 0.0, 0.0 );

insert into multi_struct_my_outers_my_inner_ms_ha values ( 5, 3, 2, 32.0, 32.1, 32.2, 32.3, 32.4, 32.5, 32.6, 32.7, 0.0, 0.0, 0.0, 0.0 );
