
-- GENERATED BY TRAD4 
delete from tier1_struct_scalar_dates;
insert into tier1_struct_scalar_dates values ( 1, 0, 0, 5000 );
insert into tier1_struct_scalar_dates values ( 1, 0, 1, 5001 );
insert into tier1_struct_scalar_dates values ( 1, 0, 2, 5002 );
