
// GENERATED BY TRAD4 

// Please see the comment at the top of test_app/gen/objects/amplifier_macros.h
//  to see what's in-scope.

#include <iostream>

#include "amplifier_wrapper.c"

using namespace std;

int calculate_amplifier( obj_loc_t obj_loc, long id )
{
    for ( int i = 0 ; i < SAMPLE_COUNT ; i++ )
    {
        T4_TEST( sample_wave[i], ( i * sample_level ));
    }

    return 1;
}

