
// GENERATED BY TRAD4 

// Please see the comment at the top of test_app/gen/objects/feed_macros.h
//  to see what's in-scope.

#include <iostream>

#include "feed_wrapper.c"

using namespace std;

void calculate_feed( obj_loc_t obj_loc, int id )
{
    feed_output = feed_value;
}

