
// GENERATED BY TRAD4 

// Please see the comment at the top of test_suite/gen/objects/tier1_macros.c
//  to see what's in-scope.

#include <iostream>

#include "tier1_wrapper.c"

using namespace std;

void calculate_tier1( obj_loc_t obj_loc, int id )
{
    T4_TEST( tier1_struct_scalar_rates( 0 ), 4.5 );
    T4_TEST( tier1_struct_scalar_dates( 0 ), 5000 );

cout << "tier1_double_array( 3 ):" << tier1_double_array( 3 ) << endl;
/*
cout << "tier1_struct_scalar_rates( 0 ):" << tier1_struct_scalar_rates( 0 ) << endl;
cout << "tier1_struct_scalar_dates( 0 ):" << tier1_struct_scalar_dates( 0 ) << endl;
cout << "tier1:" << endl;
cout << "tier1_int1:" << tier1_int1 << endl;
cout << "tier1_int2:" << tier1_int2 << endl;
//cout << "tier1_struct_scalar:" << tier1_struct_scalar << endl;
cout << "tier1_int_out:" << tier1_int_out << endl;
cout << "tier1_bool_array( index_20 ):" << tier1_bool_array( index_20 ) << endl;
//cout << "tier1_struct_vec( index_4 ):" << tier1_struct_vec( index_4 ) << endl;
cout << "tier1_struct_vec_x( index_4 ):" << tier1_struct_vec_x( index_4 ) << endl;
cout << "tier1_struct_vec_y( index_4 ):" << tier1_struct_vec_y( index_4 ) << endl;
*/
}

