
// GENERATED BY TRAD4 

// Please see the comment at the top of test_suite/gen/objects/tier1_macros.c
//  to see what's in-scope.

#include <iostream>

#include "tier1_wrapper.c"

using namespace std;

int calculate_tier1( obj_loc_t obj_loc, long id )
{
    T4_TEST( tier1_struct_scalar_rates[ 0 ], 4.0 );
    T4_TEST( tier1_struct_scalar_rates[ 2 ], 4.2 );
    T4_TEST( tier1_struct_scalar_dates[ 0 ], 5000 );
    T4_TEST( tier1_struct_scalar_dates[ 2 ], 5002 );
    T4_TEST( tier1_double_array[ 0 ], 0.14 );
    T4_TEST( tier1_double_array[ 1 ], 1.14 );
    T4_TEST( tier1_double_array[ 2 ], 2.14 );
    T4_TEST( tier1_double_array[ 3 ], 3.14 );
    T4_TEST( tier1_double_array[ 4 ], 4.14 );

    tier1_int_out = tier1_struct_scalar_dates[ 0 ] + tier1_struct_scalar_dates[ 1 ] + tier1_struct_scalar_dates[ 2 ];

    return 1;
}

