
-- GENERATED BY TRAD4 
delete from harmonic;
insert into object values ( 1, 1, 1, "harmonic_1", 1, 1 );
insert into harmonic values ( 1 );
insert into object values ( 2, 1, 1, "harmonic_2", 1, 1 );
insert into harmonic values ( 2 );
